### ISSUE TITLE
PropagationCost = 1 when player stands directly on portal to higher priority room, and sound is in lower priority room

### ISSUE THREAD

**Issue by ianberman** [VilleOjala/FMOD-Unity-Tools#5]
I noticed a slight gap in audio when you move from a lower priority room to a higher priority room (eg. from a room with priority 1 to a room with priority 2). Looking at the debugger in the Spatial Audio Manager, I can confirm that `PropagationCost` = 1 when the player is standing directly on the portal.

Steps to reproduce:
Place sound emitter in a lower priority room, and position player to stand directly on a portal to a higher priority room. I only tested this if the higher priority room _is nested within_ a larger, lower priority room. I'm not sure if it happens if they are adjacent and not nested.

(our game is also first-person, so the listener position can be quite specific)

**Comment by VilleOjala** [comment]
![Issue #5](https://user-images.githubusercontent.com/69209034/226531420-5ef11c43-ad7b-4fd5-a8f8-338a7c2d570a.PNG)

The only way I was able to quickly reproduce a similar end result, is in situations where the portal has been placed some distance inside the nested higher priority area (instead of on its border) and the listener is located in between the portal and the area border, plus the distance between listener and the portal is greater than the constant ```MinimumVectorMagnitude```.

If this is the same issue you're experiencing, you can fix it either by placing the portal more accurately on the area border or by increasing the ```MinimumVectorMagnitude```. Ideally, this could of course use a more robust solution that does not require such precision work from the user.

If the issue you're experiencing is something different, we'll have to look more closely into the repro steps.

**Comment by ianberman** [comment]
I believe this was the issue I was experiencing, and I didn't realize that my nested room slightly overlapped the portal. Thank you!
